# Generated by Django 2.2.4 on 2019-10-24 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_auto_20191024_1535'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post_reply',
            old_name='post_id',
            new_name='post',
        ),
    ]
